source 'https://github.com/CocoaPods/Specs.git'

target 'HZRButton', :exclusive => true do
  pod "HZRButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HZRButton", :path => "../"

  
end
